version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-immichframe_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: 'false'
    container_name: mateosilguero-immichframe_app_proxy_1
  server:
    image: ghcr.io/immichframe/immichframe:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    container_name: mateosilguero-immichframe_server_1