version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-octobot_octobot_1
      APP_PORT: 5001
      PROXY_AUTH_ADD: 'true'
    container_name: mateosilguero-octobot_app_proxy_1

  octobot:
    image: drakkarsoftware/octobot:1.0.10@sha256:39c179d3ad30477e35661e0277b567c1996fc3e21134c0068cc2f0538cb0be84
    labels:
      - traefik.enable=true
      - traefik.http.routers.octobot.rule=Host("localhost")
      - traefik.http.services.octobot.loadbalancer.server.port=5001
      - traefik.http.routers.octobot.tls=true
    volumes:
      - ${APP_DATA_DIR}/data/logs:/octobot/logs
      - ${APP_DATA_DIR}/data/backtesting:/octobot/backtesting
      - ${APP_DATA_DIR}/data/tentacles:/octobot/tentacles
      - ${APP_DATA_DIR}/data/user:/octobot/user
    restart: always
    expose:
      - 5001
    container_name: mateosilguero-octobot_octobot_1

  traefik:
    image: traefik:v2.5
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: mateosilguero-octobot_traefik_1