version: "3.7"

services:
  app_proxy:     
    environment:
      APP_HOST: octobot_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "true"

  server:
    image: drakkarsoftware/octobot:stable
    labels:
      - traefik.enable=true
      - traefik.http.routers.octobot.rule=Host("localhost")
      - traefik.http.services.octobot.loadbalancer.server.port=5001
      - traefik.http.routers.octobot.tls=true
    volumes:
       - ${APP_DATA_DIR}/data/logs:/octobot/logs
       - ${APP_DATA_DIR}/data/backtesting:/octobot/backtesting
       - ${APP_DATA_DIR}/data/tentacles:/octobot/tentacles
       - ${APP_DATA_DIR}/data/user:/octobot/user
    expose:
       - 5001
    restart: always

  traefik:
    image: traefik:v2.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8083:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro