version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-crafty_server_1
      APP_PORT: 8112
      PROXY_AUTH_ADD: 'false'
    container_name: mateosilguero-crafty_app_proxy_1
  server:
    image: arcadiatechnology/crafty-4:4.4.7@sha256:a2a083675b1e6442599e31dba230f2242c9f9c713e360a507ee7df205ab4689f
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8111:8000"  # HTTP
      - "8443:8443"  # HTTPS
      - "8123:8123"  # DYNMAP
      - "25500-25600:25500-25600"  # MC SERV PORT RANGE
    volumes:
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/servers:/crafty/servers
      - ${APP_DATA_DIR}/data/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/import:/crafty/import
    container_name: mateosilguero-crafty_server_1