version: '3.7'
networks:
  yabin-network:
    name: yabin-network
    driver: default
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-yabin_yabin_1
      APP_PORT: 80
      PROXY_AUTH_ADD: 'true'
    container_name: mateosilguero-yabin_app_proxy_1
  yabin:
    ports:
      - '${PORT:-5005}:${PORT:-3000}'
    image: 'yureien/yabin:latest'
    depends_on:
      - db
    networks:
      - yabin-network
    container_name: mateosilguero-yabin_yabin_1
  db:
    container_name: mateosilguero-yabin-db
    restart: always
    image: postgres:15-alpine
    expose:
      - '5432'
    environment:
      POSTGRES_USER: ${DB_USER:-yabin_user}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-123}
      POSTGRES_DB: ${DB_NAME:-yabin_db}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${APP_DATA_DIR}/db-data:/var/lib/postgresql/data
    networks:
      - yabin-network