version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-microbin_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: 'true'
    container_name: mateosilguero-microbin_app_proxy_1
  server:
    image: danielszabo99/microbin:2.0.4@sha256:c5bd4643135540a68a2846950fe4f65f3bcc94b62ed7c7644e563dfde6f1732c
    restart: always
    ports:
      - '4004:8080'
    volumes:
      - ${APP_DATA_DIR}/data:/app/microbin_data
    environment:
      MICROBIN_ENABLE_BURN_AFTER: true
      MICROBIN_QR: true
    container_name: mateosilguero-microbin_server_1