version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: mateosilguero-adventure_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: 'true'

  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:beta
    platform: linux/arm64
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=http://server:8001
      - ORIGIN=http://localhost:7000
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "7000:3000"
    depends_on:
      - server

  db:
    image: tobi312/rpi-postgresql-postgis:13-3.3-alpine-arm
    platform: linux/arm64
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: adventure
    volumes:
      - ${APP_DATA_DIR}/postgresql/data:/var/lib/postgresql/data/

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:beta
    platform: linux/arm64
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=adventure
      - SECRET_KEY=+gHIbzNHb9mEYxzF5oP8yxpzRbOQtBbe/yhrZu4qh019NUZ1
      - DJANGO_ADMIN_USERNAME=adventure
      - DJANGO_ADMIN_PASSWORD=adventure
      - DJANGO_ADMIN_EMAIL=admin@admin.com
      - PUBLIC_URL='http://localhost:8016'
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app,http://localhost:7000,http://192.168.1.5:7000,https://adventure.whare
      - DEBUG=False
      - FRONTEND_URL='https://adventure.whare'
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ${APP_DATA_DIR}/media:/code/media/